// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_vector_processor);
    __Vhier.remove(&__Vscope_vector_processor, &__Vscope_vector_processor__add_inst);
    __Vhier.remove(&__Vscope_vector_processor, &__Vscope_vector_processor__comp_inst);
    __Vhier.remove(&__Vscope_vector_processor, &__Vscope_vector_processor__div_inst);
    __Vhier.remove(&__Vscope_vector_processor, &__Vscope_vector_processor__mult_inst);
    __Vhier.remove(&__Vscope_vector_processor, &__Vscope_vector_processor__sub_inst);
    __Vhier.remove(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__0__KET____adder);
    __Vhier.remove(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__1__KET____adder);
    __Vhier.remove(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__2__KET____adder);
    __Vhier.remove(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__3__KET____adder);
    __Vhier.remove(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__4__KET____adder);
    __Vhier.remove(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__5__KET____adder);
    __Vhier.remove(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__6__KET____adder);
    __Vhier.remove(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__7__KET____adder);
    __Vhier.remove(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__0__KET____comparator);
    __Vhier.remove(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__1__KET____comparator);
    __Vhier.remove(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__2__KET____comparator);
    __Vhier.remove(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__3__KET____comparator);
    __Vhier.remove(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__4__KET____comparator);
    __Vhier.remove(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__5__KET____comparator);
    __Vhier.remove(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__6__KET____comparator);
    __Vhier.remove(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__7__KET____comparator);
    __Vhier.remove(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__0__KET____divider);
    __Vhier.remove(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__1__KET____divider);
    __Vhier.remove(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__2__KET____divider);
    __Vhier.remove(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__3__KET____divider);
    __Vhier.remove(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__4__KET____divider);
    __Vhier.remove(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__5__KET____divider);
    __Vhier.remove(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__6__KET____divider);
    __Vhier.remove(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__7__KET____divider);
    __Vhier.remove(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__0__KET____multiplier);
    __Vhier.remove(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__1__KET____multiplier);
    __Vhier.remove(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__2__KET____multiplier);
    __Vhier.remove(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__3__KET____multiplier);
    __Vhier.remove(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__4__KET____multiplier);
    __Vhier.remove(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__5__KET____multiplier);
    __Vhier.remove(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__6__KET____multiplier);
    __Vhier.remove(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__7__KET____multiplier);
    __Vhier.remove(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__0__KET____subtractor);
    __Vhier.remove(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__1__KET____subtractor);
    __Vhier.remove(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__2__KET____subtractor);
    __Vhier.remove(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__3__KET____subtractor);
    __Vhier.remove(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__4__KET____subtractor);
    __Vhier.remove(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__5__KET____subtractor);
    __Vhier.remove(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__6__KET____subtractor);
    __Vhier.remove(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__7__KET____subtractor);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(25);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_vector_processor.configure(this, name(), "vector_processor", "vector_processor", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__add_inst.configure(this, name(), "vector_processor.add_inst", "add_inst", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__add_inst__add_loop__BRA__0__KET____adder.configure(this, name(), "vector_processor.add_inst.add_loop[0].adder", "adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__add_inst__add_loop__BRA__1__KET____adder.configure(this, name(), "vector_processor.add_inst.add_loop[1].adder", "adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__add_inst__add_loop__BRA__2__KET____adder.configure(this, name(), "vector_processor.add_inst.add_loop[2].adder", "adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__add_inst__add_loop__BRA__3__KET____adder.configure(this, name(), "vector_processor.add_inst.add_loop[3].adder", "adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__add_inst__add_loop__BRA__4__KET____adder.configure(this, name(), "vector_processor.add_inst.add_loop[4].adder", "adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__add_inst__add_loop__BRA__5__KET____adder.configure(this, name(), "vector_processor.add_inst.add_loop[5].adder", "adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__add_inst__add_loop__BRA__6__KET____adder.configure(this, name(), "vector_processor.add_inst.add_loop[6].adder", "adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__add_inst__add_loop__BRA__7__KET____adder.configure(this, name(), "vector_processor.add_inst.add_loop[7].adder", "adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__comp_inst.configure(this, name(), "vector_processor.comp_inst", "comp_inst", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__comp_inst__slt_loop__BRA__0__KET____comparator.configure(this, name(), "vector_processor.comp_inst.slt_loop[0].comparator", "comparator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__comp_inst__slt_loop__BRA__1__KET____comparator.configure(this, name(), "vector_processor.comp_inst.slt_loop[1].comparator", "comparator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__comp_inst__slt_loop__BRA__2__KET____comparator.configure(this, name(), "vector_processor.comp_inst.slt_loop[2].comparator", "comparator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__comp_inst__slt_loop__BRA__3__KET____comparator.configure(this, name(), "vector_processor.comp_inst.slt_loop[3].comparator", "comparator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__comp_inst__slt_loop__BRA__4__KET____comparator.configure(this, name(), "vector_processor.comp_inst.slt_loop[4].comparator", "comparator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__comp_inst__slt_loop__BRA__5__KET____comparator.configure(this, name(), "vector_processor.comp_inst.slt_loop[5].comparator", "comparator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__comp_inst__slt_loop__BRA__6__KET____comparator.configure(this, name(), "vector_processor.comp_inst.slt_loop[6].comparator", "comparator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__comp_inst__slt_loop__BRA__7__KET____comparator.configure(this, name(), "vector_processor.comp_inst.slt_loop[7].comparator", "comparator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__div_inst.configure(this, name(), "vector_processor.div_inst", "div_inst", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__div_inst__div_loop__BRA__0__KET____divider.configure(this, name(), "vector_processor.div_inst.div_loop[0].divider", "divider", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__div_inst__div_loop__BRA__1__KET____divider.configure(this, name(), "vector_processor.div_inst.div_loop[1].divider", "divider", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__div_inst__div_loop__BRA__2__KET____divider.configure(this, name(), "vector_processor.div_inst.div_loop[2].divider", "divider", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__div_inst__div_loop__BRA__3__KET____divider.configure(this, name(), "vector_processor.div_inst.div_loop[3].divider", "divider", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__div_inst__div_loop__BRA__4__KET____divider.configure(this, name(), "vector_processor.div_inst.div_loop[4].divider", "divider", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__div_inst__div_loop__BRA__5__KET____divider.configure(this, name(), "vector_processor.div_inst.div_loop[5].divider", "divider", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__div_inst__div_loop__BRA__6__KET____divider.configure(this, name(), "vector_processor.div_inst.div_loop[6].divider", "divider", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__div_inst__div_loop__BRA__7__KET____divider.configure(this, name(), "vector_processor.div_inst.div_loop[7].divider", "divider", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__mult_inst.configure(this, name(), "vector_processor.mult_inst", "mult_inst", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__mult_inst__mul_loop__BRA__0__KET____multiplier.configure(this, name(), "vector_processor.mult_inst.mul_loop[0].multiplier", "multiplier", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__mult_inst__mul_loop__BRA__1__KET____multiplier.configure(this, name(), "vector_processor.mult_inst.mul_loop[1].multiplier", "multiplier", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__mult_inst__mul_loop__BRA__2__KET____multiplier.configure(this, name(), "vector_processor.mult_inst.mul_loop[2].multiplier", "multiplier", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__mult_inst__mul_loop__BRA__3__KET____multiplier.configure(this, name(), "vector_processor.mult_inst.mul_loop[3].multiplier", "multiplier", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__mult_inst__mul_loop__BRA__4__KET____multiplier.configure(this, name(), "vector_processor.mult_inst.mul_loop[4].multiplier", "multiplier", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__mult_inst__mul_loop__BRA__5__KET____multiplier.configure(this, name(), "vector_processor.mult_inst.mul_loop[5].multiplier", "multiplier", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__mult_inst__mul_loop__BRA__6__KET____multiplier.configure(this, name(), "vector_processor.mult_inst.mul_loop[6].multiplier", "multiplier", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__mult_inst__mul_loop__BRA__7__KET____multiplier.configure(this, name(), "vector_processor.mult_inst.mul_loop[7].multiplier", "multiplier", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__sub_inst.configure(this, name(), "vector_processor.sub_inst", "sub_inst", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__sub_inst__sub_loop__BRA__0__KET____subtractor.configure(this, name(), "vector_processor.sub_inst.sub_loop[0].subtractor", "subtractor", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__sub_inst__sub_loop__BRA__1__KET____subtractor.configure(this, name(), "vector_processor.sub_inst.sub_loop[1].subtractor", "subtractor", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__sub_inst__sub_loop__BRA__2__KET____subtractor.configure(this, name(), "vector_processor.sub_inst.sub_loop[2].subtractor", "subtractor", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__sub_inst__sub_loop__BRA__3__KET____subtractor.configure(this, name(), "vector_processor.sub_inst.sub_loop[3].subtractor", "subtractor", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__sub_inst__sub_loop__BRA__4__KET____subtractor.configure(this, name(), "vector_processor.sub_inst.sub_loop[4].subtractor", "subtractor", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__sub_inst__sub_loop__BRA__5__KET____subtractor.configure(this, name(), "vector_processor.sub_inst.sub_loop[5].subtractor", "subtractor", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__sub_inst__sub_loop__BRA__6__KET____subtractor.configure(this, name(), "vector_processor.sub_inst.sub_loop[6].subtractor", "subtractor", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_vector_processor__sub_inst__sub_loop__BRA__7__KET____subtractor.configure(this, name(), "vector_processor.sub_inst.sub_loop[7].subtractor", "subtractor", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_vector_processor);
    __Vhier.add(&__Vscope_vector_processor, &__Vscope_vector_processor__add_inst);
    __Vhier.add(&__Vscope_vector_processor, &__Vscope_vector_processor__comp_inst);
    __Vhier.add(&__Vscope_vector_processor, &__Vscope_vector_processor__div_inst);
    __Vhier.add(&__Vscope_vector_processor, &__Vscope_vector_processor__mult_inst);
    __Vhier.add(&__Vscope_vector_processor, &__Vscope_vector_processor__sub_inst);
    __Vhier.add(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__0__KET____adder);
    __Vhier.add(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__1__KET____adder);
    __Vhier.add(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__2__KET____adder);
    __Vhier.add(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__3__KET____adder);
    __Vhier.add(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__4__KET____adder);
    __Vhier.add(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__5__KET____adder);
    __Vhier.add(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__6__KET____adder);
    __Vhier.add(&__Vscope_vector_processor__add_inst, &__Vscope_vector_processor__add_inst__add_loop__BRA__7__KET____adder);
    __Vhier.add(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__0__KET____comparator);
    __Vhier.add(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__1__KET____comparator);
    __Vhier.add(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__2__KET____comparator);
    __Vhier.add(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__3__KET____comparator);
    __Vhier.add(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__4__KET____comparator);
    __Vhier.add(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__5__KET____comparator);
    __Vhier.add(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__6__KET____comparator);
    __Vhier.add(&__Vscope_vector_processor__comp_inst, &__Vscope_vector_processor__comp_inst__slt_loop__BRA__7__KET____comparator);
    __Vhier.add(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__0__KET____divider);
    __Vhier.add(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__1__KET____divider);
    __Vhier.add(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__2__KET____divider);
    __Vhier.add(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__3__KET____divider);
    __Vhier.add(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__4__KET____divider);
    __Vhier.add(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__5__KET____divider);
    __Vhier.add(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__6__KET____divider);
    __Vhier.add(&__Vscope_vector_processor__div_inst, &__Vscope_vector_processor__div_inst__div_loop__BRA__7__KET____divider);
    __Vhier.add(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__0__KET____multiplier);
    __Vhier.add(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__1__KET____multiplier);
    __Vhier.add(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__2__KET____multiplier);
    __Vhier.add(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__3__KET____multiplier);
    __Vhier.add(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__4__KET____multiplier);
    __Vhier.add(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__5__KET____multiplier);
    __Vhier.add(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__6__KET____multiplier);
    __Vhier.add(&__Vscope_vector_processor__mult_inst, &__Vscope_vector_processor__mult_inst__mul_loop__BRA__7__KET____multiplier);
    __Vhier.add(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__0__KET____subtractor);
    __Vhier.add(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__1__KET____subtractor);
    __Vhier.add(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__2__KET____subtractor);
    __Vhier.add(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__3__KET____subtractor);
    __Vhier.add(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__4__KET____subtractor);
    __Vhier.add(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__5__KET____subtractor);
    __Vhier.add(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__6__KET____subtractor);
    __Vhier.add(&__Vscope_vector_processor__sub_inst, &__Vscope_vector_processor__sub_inst__sub_loop__BRA__7__KET____subtractor);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"operation", &(TOP.operation), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"result", &(TOP.result), false, VLVT_WDATA,VLVD_OUT|VLVF_PUB_RW,1 ,255,0);
        __Vscope_TOP.varInsert(__Vfinal,"scalar", &(TOP.scalar), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"vec_a", &(TOP.vec_a), false, VLVT_WDATA,VLVD_IN|VLVF_PUB_RW,1 ,255,0);
        __Vscope_TOP.varInsert(__Vfinal,"vec_b", &(TOP.vec_b), false, VLVT_WDATA,VLVD_IN|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor.varInsert(__Vfinal,"add_result", &(TOP.vector_processor__DOT__add_result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor.varInsert(__Vfinal,"div_result", &(TOP.vector_processor__DOT__div_result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor.varInsert(__Vfinal,"mul_result", &(TOP.vector_processor__DOT__mul_result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor.varInsert(__Vfinal,"operation", &(TOP.vector_processor__DOT__operation), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_vector_processor.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor.varInsert(__Vfinal,"scalar", &(TOP.vector_processor__DOT__scalar), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor.varInsert(__Vfinal,"slt_result", &(TOP.vector_processor__DOT__slt_result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor.varInsert(__Vfinal,"sub_result", &(TOP.vector_processor__DOT__sub_result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor.varInsert(__Vfinal,"vec_a", &(TOP.vector_processor__DOT__vec_a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor.varInsert(__Vfinal,"vec_b", &(TOP.vector_processor__DOT__vec_b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__add_inst.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__add_inst__DOT__result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__add_inst.varInsert(__Vfinal,"vec_a", &(TOP.vector_processor__DOT__add_inst__DOT__vec_a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__add_inst.varInsert(__Vfinal,"vec_b", &(TOP.vector_processor__DOT__add_inst__DOT__vec_b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__0__KET____adder.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__0__KET____DOT__adder__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__0__KET____adder.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__0__KET____DOT__adder__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__0__KET____adder.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__0__KET____DOT__adder__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__0__KET____adder.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__0__KET____DOT__adder__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__0__KET____adder.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__0__KET____DOT__adder__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__0__KET____adder.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__0__KET____DOT__adder__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__1__KET____adder.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__1__KET____DOT__adder__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__1__KET____adder.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__1__KET____DOT__adder__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__1__KET____adder.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__1__KET____DOT__adder__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__1__KET____adder.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__1__KET____DOT__adder__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__1__KET____adder.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__1__KET____DOT__adder__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__1__KET____adder.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__1__KET____DOT__adder__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__2__KET____adder.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__2__KET____DOT__adder__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__2__KET____adder.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__2__KET____DOT__adder__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__2__KET____adder.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__2__KET____DOT__adder__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__2__KET____adder.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__2__KET____DOT__adder__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__2__KET____adder.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__2__KET____DOT__adder__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__2__KET____adder.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__2__KET____DOT__adder__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__3__KET____adder.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__3__KET____DOT__adder__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__3__KET____adder.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__3__KET____DOT__adder__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__3__KET____adder.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__3__KET____DOT__adder__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__3__KET____adder.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__3__KET____DOT__adder__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__3__KET____adder.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__3__KET____DOT__adder__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__3__KET____adder.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__3__KET____DOT__adder__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__4__KET____adder.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__4__KET____DOT__adder__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__4__KET____adder.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__4__KET____DOT__adder__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__4__KET____adder.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__4__KET____DOT__adder__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__4__KET____adder.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__4__KET____DOT__adder__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__4__KET____adder.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__4__KET____DOT__adder__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__4__KET____adder.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__4__KET____DOT__adder__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__5__KET____adder.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__5__KET____DOT__adder__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__5__KET____adder.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__5__KET____DOT__adder__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__5__KET____adder.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__5__KET____DOT__adder__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__5__KET____adder.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__5__KET____DOT__adder__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__5__KET____adder.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__5__KET____DOT__adder__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__5__KET____adder.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__5__KET____DOT__adder__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__6__KET____adder.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__6__KET____DOT__adder__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__6__KET____adder.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__6__KET____DOT__adder__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__6__KET____adder.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__6__KET____DOT__adder__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__6__KET____adder.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__6__KET____DOT__adder__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__6__KET____adder.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__6__KET____DOT__adder__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__6__KET____adder.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__6__KET____DOT__adder__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__7__KET____adder.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__7__KET____DOT__adder__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__7__KET____adder.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__7__KET____DOT__adder__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__7__KET____adder.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__7__KET____DOT__adder__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__7__KET____adder.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__7__KET____DOT__adder__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__7__KET____adder.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__7__KET____DOT__adder__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__add_inst__add_loop__BRA__7__KET____adder.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__add_inst__DOT__add_loop__BRA__7__KET____DOT__adder__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__comp_inst__DOT__result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__comp_inst.varInsert(__Vfinal,"vec_a", &(TOP.vector_processor__DOT__comp_inst__DOT__vec_a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__comp_inst.varInsert(__Vfinal,"vec_b", &(TOP.vector_processor__DOT__comp_inst__DOT__vec_b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__0__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ONE", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__0__KET____DOT__comparator__DOT__FIXED_POINT_ONE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__0__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ZERO", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__0__KET____DOT__comparator__DOT__FIXED_POINT_ZERO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__0__KET____comparator.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__0__KET____DOT__comparator__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__0__KET____comparator.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__0__KET____DOT__comparator__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__0__KET____comparator.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__0__KET____DOT__comparator__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__1__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ONE", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__1__KET____DOT__comparator__DOT__FIXED_POINT_ONE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__1__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ZERO", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__1__KET____DOT__comparator__DOT__FIXED_POINT_ZERO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__1__KET____comparator.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__1__KET____DOT__comparator__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__1__KET____comparator.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__1__KET____DOT__comparator__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__1__KET____comparator.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__1__KET____DOT__comparator__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__2__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ONE", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__2__KET____DOT__comparator__DOT__FIXED_POINT_ONE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__2__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ZERO", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__2__KET____DOT__comparator__DOT__FIXED_POINT_ZERO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__2__KET____comparator.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__2__KET____DOT__comparator__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__2__KET____comparator.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__2__KET____DOT__comparator__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__2__KET____comparator.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__2__KET____DOT__comparator__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__3__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ONE", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__3__KET____DOT__comparator__DOT__FIXED_POINT_ONE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__3__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ZERO", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__3__KET____DOT__comparator__DOT__FIXED_POINT_ZERO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__3__KET____comparator.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__3__KET____DOT__comparator__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__3__KET____comparator.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__3__KET____DOT__comparator__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__3__KET____comparator.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__3__KET____DOT__comparator__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__4__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ONE", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__4__KET____DOT__comparator__DOT__FIXED_POINT_ONE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__4__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ZERO", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__4__KET____DOT__comparator__DOT__FIXED_POINT_ZERO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__4__KET____comparator.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__4__KET____DOT__comparator__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__4__KET____comparator.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__4__KET____DOT__comparator__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__4__KET____comparator.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__4__KET____DOT__comparator__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__5__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ONE", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__5__KET____DOT__comparator__DOT__FIXED_POINT_ONE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__5__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ZERO", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__5__KET____DOT__comparator__DOT__FIXED_POINT_ZERO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__5__KET____comparator.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__5__KET____DOT__comparator__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__5__KET____comparator.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__5__KET____DOT__comparator__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__5__KET____comparator.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__5__KET____DOT__comparator__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__6__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ONE", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__6__KET____DOT__comparator__DOT__FIXED_POINT_ONE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__6__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ZERO", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__6__KET____DOT__comparator__DOT__FIXED_POINT_ZERO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__6__KET____comparator.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__6__KET____DOT__comparator__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__6__KET____comparator.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__6__KET____DOT__comparator__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__6__KET____comparator.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__6__KET____DOT__comparator__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__7__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ONE", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__7__KET____DOT__comparator__DOT__FIXED_POINT_ONE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__7__KET____comparator.varInsert(__Vfinal,"FIXED_POINT_ZERO", const_cast<void*>(static_cast<const void*>(&(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__7__KET____DOT__comparator__DOT__FIXED_POINT_ZERO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__7__KET____comparator.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__7__KET____DOT__comparator__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__7__KET____comparator.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__7__KET____DOT__comparator__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__comp_inst__slt_loop__BRA__7__KET____comparator.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__comp_inst__DOT__slt_loop__BRA__7__KET____DOT__comparator__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__div_inst__DOT__result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__div_inst.varInsert(__Vfinal,"scalar", &(TOP.vector_processor__DOT__div_inst__DOT__scalar), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst.varInsert(__Vfinal,"vec_a", &(TOP.vector_processor__DOT__div_inst__DOT__vec_a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__0__KET____divider.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__0__KET____DOT__divider__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__0__KET____divider.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__0__KET____DOT__divider__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__0__KET____divider.varInsert(__Vfinal,"dividend", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__0__KET____DOT__divider__DOT__dividend), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__0__KET____divider.varInsert(__Vfinal,"divisor", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__0__KET____DOT__divider__DOT__divisor), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__0__KET____divider.varInsert(__Vfinal,"quotient", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__0__KET____DOT__divider__DOT__quotient), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__0__KET____divider.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__0__KET____DOT__divider__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__1__KET____divider.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__1__KET____DOT__divider__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__1__KET____divider.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__1__KET____DOT__divider__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__1__KET____divider.varInsert(__Vfinal,"dividend", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__1__KET____DOT__divider__DOT__dividend), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__1__KET____divider.varInsert(__Vfinal,"divisor", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__1__KET____DOT__divider__DOT__divisor), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__1__KET____divider.varInsert(__Vfinal,"quotient", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__1__KET____DOT__divider__DOT__quotient), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__1__KET____divider.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__1__KET____DOT__divider__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__2__KET____divider.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__2__KET____DOT__divider__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__2__KET____divider.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__2__KET____DOT__divider__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__2__KET____divider.varInsert(__Vfinal,"dividend", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__2__KET____DOT__divider__DOT__dividend), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__2__KET____divider.varInsert(__Vfinal,"divisor", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__2__KET____DOT__divider__DOT__divisor), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__2__KET____divider.varInsert(__Vfinal,"quotient", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__2__KET____DOT__divider__DOT__quotient), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__2__KET____divider.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__2__KET____DOT__divider__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__3__KET____divider.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__3__KET____DOT__divider__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__3__KET____divider.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__3__KET____DOT__divider__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__3__KET____divider.varInsert(__Vfinal,"dividend", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__3__KET____DOT__divider__DOT__dividend), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__3__KET____divider.varInsert(__Vfinal,"divisor", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__3__KET____DOT__divider__DOT__divisor), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__3__KET____divider.varInsert(__Vfinal,"quotient", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__3__KET____DOT__divider__DOT__quotient), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__3__KET____divider.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__3__KET____DOT__divider__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__4__KET____divider.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__4__KET____DOT__divider__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__4__KET____divider.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__4__KET____DOT__divider__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__4__KET____divider.varInsert(__Vfinal,"dividend", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__4__KET____DOT__divider__DOT__dividend), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__4__KET____divider.varInsert(__Vfinal,"divisor", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__4__KET____DOT__divider__DOT__divisor), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__4__KET____divider.varInsert(__Vfinal,"quotient", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__4__KET____DOT__divider__DOT__quotient), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__4__KET____divider.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__4__KET____DOT__divider__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__5__KET____divider.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__5__KET____DOT__divider__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__5__KET____divider.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__5__KET____DOT__divider__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__5__KET____divider.varInsert(__Vfinal,"dividend", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__5__KET____DOT__divider__DOT__dividend), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__5__KET____divider.varInsert(__Vfinal,"divisor", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__5__KET____DOT__divider__DOT__divisor), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__5__KET____divider.varInsert(__Vfinal,"quotient", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__5__KET____DOT__divider__DOT__quotient), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__5__KET____divider.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__5__KET____DOT__divider__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__6__KET____divider.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__6__KET____DOT__divider__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__6__KET____divider.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__6__KET____DOT__divider__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__6__KET____divider.varInsert(__Vfinal,"dividend", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__6__KET____DOT__divider__DOT__dividend), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__6__KET____divider.varInsert(__Vfinal,"divisor", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__6__KET____DOT__divider__DOT__divisor), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__6__KET____divider.varInsert(__Vfinal,"quotient", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__6__KET____DOT__divider__DOT__quotient), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__6__KET____divider.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__6__KET____DOT__divider__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__7__KET____divider.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__7__KET____DOT__divider__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__7__KET____divider.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__7__KET____DOT__divider__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__7__KET____divider.varInsert(__Vfinal,"dividend", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__7__KET____DOT__divider__DOT__dividend), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__7__KET____divider.varInsert(__Vfinal,"divisor", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__7__KET____DOT__divider__DOT__divisor), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__7__KET____divider.varInsert(__Vfinal,"quotient", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__7__KET____DOT__divider__DOT__quotient), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__div_inst__div_loop__BRA__7__KET____divider.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__div_inst__DOT__div_loop__BRA__7__KET____DOT__divider__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__mult_inst__DOT__result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__mult_inst.varInsert(__Vfinal,"scalar", &(TOP.vector_processor__DOT__mult_inst__DOT__scalar), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst.varInsert(__Vfinal,"vec_a", &(TOP.vector_processor__DOT__mult_inst__DOT__vec_a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__0__KET____multiplier.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__0__KET____DOT__multiplier__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__0__KET____multiplier.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__0__KET____DOT__multiplier__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__0__KET____multiplier.varInsert(__Vfinal,"product", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__0__KET____DOT__multiplier__DOT__product), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__0__KET____multiplier.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__0__KET____DOT__multiplier__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__1__KET____multiplier.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__1__KET____DOT__multiplier__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__1__KET____multiplier.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__1__KET____DOT__multiplier__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__1__KET____multiplier.varInsert(__Vfinal,"product", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__1__KET____DOT__multiplier__DOT__product), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__1__KET____multiplier.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__1__KET____DOT__multiplier__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__2__KET____multiplier.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__2__KET____DOT__multiplier__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__2__KET____multiplier.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__2__KET____DOT__multiplier__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__2__KET____multiplier.varInsert(__Vfinal,"product", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__2__KET____DOT__multiplier__DOT__product), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__2__KET____multiplier.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__2__KET____DOT__multiplier__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__3__KET____multiplier.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__3__KET____DOT__multiplier__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__3__KET____multiplier.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__3__KET____DOT__multiplier__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__3__KET____multiplier.varInsert(__Vfinal,"product", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__3__KET____DOT__multiplier__DOT__product), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__3__KET____multiplier.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__3__KET____DOT__multiplier__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__4__KET____multiplier.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__4__KET____DOT__multiplier__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__4__KET____multiplier.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__4__KET____DOT__multiplier__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__4__KET____multiplier.varInsert(__Vfinal,"product", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__4__KET____DOT__multiplier__DOT__product), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__4__KET____multiplier.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__4__KET____DOT__multiplier__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__5__KET____multiplier.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__5__KET____DOT__multiplier__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__5__KET____multiplier.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__5__KET____DOT__multiplier__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__5__KET____multiplier.varInsert(__Vfinal,"product", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__5__KET____DOT__multiplier__DOT__product), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__5__KET____multiplier.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__5__KET____DOT__multiplier__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__6__KET____multiplier.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__6__KET____DOT__multiplier__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__6__KET____multiplier.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__6__KET____DOT__multiplier__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__6__KET____multiplier.varInsert(__Vfinal,"product", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__6__KET____DOT__multiplier__DOT__product), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__6__KET____multiplier.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__6__KET____DOT__multiplier__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__7__KET____multiplier.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__7__KET____DOT__multiplier__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__7__KET____multiplier.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__7__KET____DOT__multiplier__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__7__KET____multiplier.varInsert(__Vfinal,"product", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__7__KET____DOT__multiplier__DOT__product), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_vector_processor__mult_inst__mul_loop__BRA__7__KET____multiplier.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__mult_inst__DOT__mul_loop__BRA__7__KET____DOT__multiplier__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__sub_inst__DOT__result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__sub_inst.varInsert(__Vfinal,"vec_a", &(TOP.vector_processor__DOT__sub_inst__DOT__vec_a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__sub_inst.varInsert(__Vfinal,"vec_b", &(TOP.vector_processor__DOT__sub_inst__DOT__vec_b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,255,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__0__KET____subtractor.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__0__KET____DOT__subtractor__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__0__KET____subtractor.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__0__KET____DOT__subtractor__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__0__KET____subtractor.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__0__KET____DOT__subtractor__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__0__KET____subtractor.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__0__KET____DOT__subtractor__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__0__KET____subtractor.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__0__KET____DOT__subtractor__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__0__KET____subtractor.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__0__KET____DOT__subtractor__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__1__KET____subtractor.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__1__KET____DOT__subtractor__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__1__KET____subtractor.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__1__KET____DOT__subtractor__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__1__KET____subtractor.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__1__KET____DOT__subtractor__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__1__KET____subtractor.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__1__KET____DOT__subtractor__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__1__KET____subtractor.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__1__KET____DOT__subtractor__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__1__KET____subtractor.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__1__KET____DOT__subtractor__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__2__KET____subtractor.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__2__KET____DOT__subtractor__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__2__KET____subtractor.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__2__KET____DOT__subtractor__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__2__KET____subtractor.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__2__KET____DOT__subtractor__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__2__KET____subtractor.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__2__KET____DOT__subtractor__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__2__KET____subtractor.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__2__KET____DOT__subtractor__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__2__KET____subtractor.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__2__KET____DOT__subtractor__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__3__KET____subtractor.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__3__KET____DOT__subtractor__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__3__KET____subtractor.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__3__KET____DOT__subtractor__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__3__KET____subtractor.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__3__KET____DOT__subtractor__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__3__KET____subtractor.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__3__KET____DOT__subtractor__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__3__KET____subtractor.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__3__KET____DOT__subtractor__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__3__KET____subtractor.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__3__KET____DOT__subtractor__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__4__KET____subtractor.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__4__KET____DOT__subtractor__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__4__KET____subtractor.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__4__KET____DOT__subtractor__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__4__KET____subtractor.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__4__KET____DOT__subtractor__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__4__KET____subtractor.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__4__KET____DOT__subtractor__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__4__KET____subtractor.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__4__KET____DOT__subtractor__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__4__KET____subtractor.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__4__KET____DOT__subtractor__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__5__KET____subtractor.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__5__KET____DOT__subtractor__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__5__KET____subtractor.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__5__KET____DOT__subtractor__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__5__KET____subtractor.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__5__KET____DOT__subtractor__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__5__KET____subtractor.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__5__KET____DOT__subtractor__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__5__KET____subtractor.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__5__KET____DOT__subtractor__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__5__KET____subtractor.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__5__KET____DOT__subtractor__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__6__KET____subtractor.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__6__KET____DOT__subtractor__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__6__KET____subtractor.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__6__KET____DOT__subtractor__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__6__KET____subtractor.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__6__KET____DOT__subtractor__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__6__KET____subtractor.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__6__KET____DOT__subtractor__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__6__KET____subtractor.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__6__KET____DOT__subtractor__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__6__KET____subtractor.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__6__KET____DOT__subtractor__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__7__KET____subtractor.varInsert(__Vfinal,"a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__7__KET____DOT__subtractor__DOT__a), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__7__KET____subtractor.varInsert(__Vfinal,"b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__7__KET____DOT__subtractor__DOT__b), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__7__KET____subtractor.varInsert(__Vfinal,"extended_a", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__7__KET____DOT__subtractor__DOT__extended_a), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__7__KET____subtractor.varInsert(__Vfinal,"extended_b", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__7__KET____DOT__subtractor__DOT__extended_b), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__7__KET____subtractor.varInsert(__Vfinal,"extended_result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__7__KET____DOT__subtractor__DOT__extended_result), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_vector_processor__sub_inst__sub_loop__BRA__7__KET____subtractor.varInsert(__Vfinal,"result", &(TOP.vector_processor__DOT__sub_inst__DOT__sub_loop__BRA__7__KET____DOT__subtractor__DOT__result), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
    }
}
